TysBooks/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TysBooks.Models;
namespace TysBooks.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

TysBooks/Components/CategoryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TysBooks.Models;

namespace TysBooks.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private ITysBooksRepository repo { get; set; }

        public CategoryViewComponent (ITysBooksRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);


            return View(categories);
        }
    }
}

TysBooks/Views/Shared/BookSummary.cshtml
@{
}

@model Books

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>$@Model.Price.ToString()</small>
            </span>
        </h4>
    </div>

    <div style="font-weight: bold" class="card-text p-1">@Model.Author</div>
    <br />
    <div class="card-text p-2">Publisher: @Model.Publisher</div>
    <div class="card-text p-2">ISBN: @Model.Isbn</div>
    <div class="card-text p-2">Classification: @Model.Classification</div>
    <div class="card-text p-2">Category: @Model.Category</div>
    <div class="card-text p-2">@Model.PageCount Pages</div>

    <form method="post" asp-page="/Buy">

        <input type="hidden" asp-for="@Model.BookId" />

        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>

    </form>
</div>

TysBooks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body style="background-color: aliceblue">
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand" style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; font-size: 50px">TYS BOOKS</div>
                <i style="padding-top: 17px" class="fa-3x fa fa-regular fa-book"></i>
                <div style="padding-top: 25px" class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">

        <div id="categories" class="col-3  btn-block">
            <br />
            <vc:category></vc:category>
        </div>

        <div class="col-9 btn-block">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>


    <footer style="background-color: whitesmoke" class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission7 - Tyler Harris
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>