TysBooks/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TysBooks.Models;

namespace TysBooks.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }

        private Cart cart { get; set; }

        public PurchaseController (IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        [HttpGet]

        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]

        public IActionResult Checkout(Purchase purchase)
        {
            if(cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/PurchaseConfirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

TysBooks/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TysBooks.Infrastructure;
using TysBooks.Models;

namespace TysBooks.Pages
{
    public class BuyModel : PageModel
    {
        private ITysBooksRepository repo { get; set; }

        public Cart cart { get; set; }

        public string ReturnUrl { get; set; }

        public BuyModel (ITysBooksRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove (int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

TysBooks/Pages/PurchaseConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TysBooks.Pages
{
    public class PurchaseConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TysBooks/Pages/Buy.cshtml
@page
@model TysBooks.Pages.BuyModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.cart.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price.ToString("c")</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>@Model.cart.CalculateTotal().ToString("c") </td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary"  asp-controller="Purchase" asp-action="Checkout">Checkout</a>
</div>

TysBooks/Pages/PurchaseConfirmation.cshtml
@page
@model TysBooks.Pages.PurchaseConfirmationModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order will be delivered soon!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

TysBooks/Pages/_BuyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand" style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; font-size: 50px">TYS BOOKS</div>
                <i style="padding-top: 17px" class="fa-3x fa fa-regular fa-book"></i>
            </div>
        </div>
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>

</body>
</html>